Sketch2Code/Sketch2Code.Web/Controllers/AppController.cs
using Sketch2Code.Core;
using Sketch2Code.Core.Services.Interfaces;
using Sketch2Code.Web.Models;
using Newtonsoft.Json;
using System;
using System.Configuration;
using System.IO;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Drawing;
using Sketch2Code.Core.Helpers;
using System.Text;
using System.Linq;
using Sketch2Code.Web.Helpers;
using Sketch2Code.Core.BoxGeometry;
using System.Net;

namespace Sketch2Code.Web.Controllers
{

    public class AppController : BaseController
    {
        IObjectDetectionAppService _objectDetectionAppService;
        public AppController()
        {
            _objectDetectionAppService = new ObjectDetectionAppService();
        }
        public async Task<ActionResult> Index()
        {
            return View();
        }
        [HttpPost]
        public async Task<ActionResult> Step2()
        {
            byte[] buffer = null;
            HttpPostedFileBase file = Request.Files["imageData"];
            
            //file or base64 content
            if (file == null) //check if image is submitted as base64
            {
                var image = Request["imageData"];
                if (!String.IsNullOrWhiteSpace(image))
                {
                    buffer = Convert.FromBase64String(image);
                }
                else
                {
                    throw new ApplicationException("No file or base64 content found");
                }
            }
            else
            {
                buffer = new byte[file.ContentLength];
                using (var ms = new MemoryStream())
                {
                    await file.InputStream.CopyToAsync(ms);
                    buffer = ms.ToArray();
                }
            }

            //Optimize size and quality for best performance
            buffer = ImageHelper.OptimizeImage(buffer, 100, 40);

            //generate correlationid
            var correlationID = Guid.NewGuid().ToString();

            //save the file on the storage
            var objectDetector = new ObjectDetectionAppService();
            await objectDetector.SaveResults(buffer, correlationID, "original.png");

            //Jump directly to progress
            return View("step3", new ContentViewModel { CorrelationId= correlationID });
        }

        [HttpPost]
        public async Task<ActionResult> Step2FromSample()
        {
            string Url =  Request.Url.Scheme + "://" + Request.Url.Authority + "/Content/img/sampledesigns/" + Request.Url.Segments[Request.Url.Segments.Length - 1] + ".jpg";

            byte[] buffer;
            var webRequest = WebRequest.Create(Url);

            using (var response = webRequest.GetResponse())
            using (var content = response.GetResponseStream())
            {
                var img = Image.FromStream(content);
                MemoryStream ms = new MemoryStream();
                img.Save(ms, System.Drawing.Imaging.ImageFormat.Jpeg);
                buffer = ms.ToArray();
            }
            
            //Optimize size and quality for best performance
            buffer = ImageHelper.OptimizeImage(buffer, 100, 40);

            //generate correlationid
            var correlationID = Guid.NewGuid().ToString();

            //save the file on the storage
            var objectDetector = new ObjectDetectionAppService();
            await objectDetector.SaveResults(buffer, correlationID, "original.png");

            //Jump directly to progress
            return View("step3", new ContentViewModel { CorrelationId = correlationID });
        }

        [HttpPost]
        public async Task<ActionResult> Step3()
        {
            var image = Request["imageData"];
            if (String.IsNullOrWhiteSpace(image))
                throw new ApplicationException("No file or base64 content found");

            var model = new ContentViewModel { ImageData = image };
            return View(model);
        }
        [HttpPost]        
        public async Task<JsonResult> Upload()
        {
            //var image = Request["imageData"];
            string correlationId = Request["correlationId"];

            //return await callBackEndFunction(image);
            return await callBackEnd(correlationId);
        }

        private async Task<JsonResult> callBackEndFunction(string image)
        {
            var url = ConfigurationManager.AppSettings["Sketch2CodeAppFunctionEndPoint"];

            if (String.IsNullOrWhiteSpace(image))
                throw new ApplicationException("No file or base64 content found");

            using (HttpClient client = new HttpClient())
            {
                var content = new ByteArrayContent(Convert.FromBase64String(image));
                HttpResponseMessage respon = await client.PostAsync(url, content);
                var responseBody = await respon.Content.ReadAsStringAsync();
                var jsonResponse = await Task.Run(() => JsonConvert.DeserializeObject<string>(responseBody));
                string correlationID = jsonResponse;
                return Json(new { id = correlationID });
            }
        }

        public async Task<JsonResult> callBackEnd(string correlationId)
        {
            //Pass byte array to object detector app service 
            var objectDetector = new ObjectDetectionAppService();
            byte[] content = await objectDetector.GetFile(correlationId, "original.png");
            var html = "";

            var result = await objectDetector.GetPredictionAsync(content);

            if (result != null)
            {
                byte[] jsonContent = Encoding.UTF8.GetBytes(JsonConvert.SerializeObject(result));
                await saveResults(correlationId, objectDetector, content, result, jsonContent);

                var groupBox = await objectDetector.CreateGroupBoxAsync(result);
                html = this.RenderViewToString2<GroupBox>("/Views/Layout/RawGroupBox2.cshtml", groupBox);
                await saveResults2(correlationId, objectDetector, groupBox, html);
            }

            return Json(new { id = correlationId, generatedHtml=html });
        }

        private static async Task saveResults(string correlationId, ObjectDetectionAppService objectDetector, byte[] content, System.Collections.Generic.IList<Core.Entities.PredictedObject> result, byte[] jsonContent)
        {
            //TODO: Skip this once we generate online slices
            await objectDetector.SaveResults(result, correlationId);

            await objectDetector.SaveResults(content.DrawRectangle(result), correlationId, "predicted.png");

            //TODO: Store this as Text
            await objectDetector.SaveResults(jsonContent, correlationId, "results.json");
            
        }

        private static async Task saveResults2(string correlationId, ObjectDetectionAppService objectDetector, GroupBox groupBox, string html)
        {
            //TODO: Store this as Text
            await objectDetector.SaveResults(Encoding.UTF8.GetBytes(JsonConvert.SerializeObject(groupBox)), correlationId, "groups.json");

            await objectDetector.SaveHtmlResults(html, correlationId, "generated.html");
        }

        public async Task<ActionResult> Step4(string id)
        {
            byte[] data = await _objectDetectionAppService.GetFile(id, "generated.html");
            string html = Encoding.UTF8.GetString(data);
            var model = new GeneratedHtmlModel { Html = html, FolderId = id };
            return View(model);
        }

        public async Task<ActionResult> Step5(string id)
        {
            byte[] data = await _objectDetectionAppService.GetFile(id, "generated.html");
            string html = Encoding.UTF8.GetString(data);

            //If generated HTML image is done pass it to the view
            //Check if the file is there in the storage
            var model = new GeneratedHtmlModel { Html = html, FolderId=id };
            return View(model);
        }

        public async Task<ActionResult> TakeSnapshot()
        {
            return View();
        }
        public async Task<ActionResult> Details(string id)
        {

                var model = new PredictionDetailsViewModel();

                model.Detail = await _objectDetectionAppService.GetPredictionAsync(id);
                
                if (model.Detail?.PredictedObjects != null)
                {
                    model.Name = id;
                }

                return View("Details", model);

        }
        public async Task<FileContentResult> File(string container, string fileName)
        {
            var fileContent = await this._objectDetectionAppService.GetFile(container, fileName);
            return new FileContentResult(fileContent, "image/png");
        }

        public async Task<ActionResult> Loader1()
        {
            return View();
        }
        public async Task<ActionResult> Loader2()
        {
            return View();
        }

        
        [HttpPost]
        public async Task<JsonResult> SaveFile()
        {
            var data = Request["imgBase64"];
            var folderId = Request["folderId"];

            byte[] content = Convert.FromBase64String(data);

            var objectDetector = new ObjectDetectionAppService();
            await objectDetector.SaveResults(content, folderId, "html.png");

            return Json(new { folderId = folderId });
        }
    }
}

Sketch2Code/Sketch2Code.Web/Views/App/Details.cshtml
@model Sketch2Code.Web.Models.PredictionDetailsViewModel
@{
    var blobStorageUrl = System.Configuration.ConfigurationManager.AppSettings["storageUrl"];
    var originalFileName = $"{blobStorageUrl}/{Model.Name}/original.png";
    var predictedFileName = $"{blobStorageUrl}/{Model.Name}/predicted.png";
    var htmlFileName = $"{blobStorageUrl}/{Model.Name}/html.png";
    Layout = "~/Views/Shared/_main.cshtml";
}

@section Scripts{
    <script>
        $(document).ready(function () {
            $("#step3").addClass("active");
            $("#step3txt").addClass("active");
            $("#step2").removeClass("active");
            $("#step2txt").removeClass("active");
            $("#step1").removeClass("active");
            $("#step1txt").removeClass("active");

        });
    </script>
    }


    <div class="container-fluid">
        <div class="row detailsPage_row">

            <div class="col">
                <h3 class="subtitle3 text-top text-center">SKETCH</h3>
            </div>

            <div class="col">
                <h3 class="subtitle3 text-top text-center">PREDICTED</h3>
            </div>

            <div class="col">
                <h3 class="subtitle3 text-top text-center">HTML</h3>
            </div>


        </div>
        <div class="row">

            <div class="col  bg-white align-content-center center-vt mr-2 ml-2">
                <img alt="Your sketch" class="img-fluid" src="@originalFileName" />
            </div>
            <div class="col  bg-white align-content-center center-vt ml-2 mr-2">
                <img alt="Your predicted skecth" class="img-fluid" src="@predictedFileName" />
            </div>
            <div class="col  bg-white align-content-center center-vt ml-2 mr-2">
                <img alt="Your html code" class="img-fluid" src="@htmlFileName">
            </div>

        </div>


    </div>
    <div class="container-float pt-5 mb-5">
        <div class="row justify-content-center">


            <h4 id="text-predicted" class="subtitle3 d-flex justify-content-center">PREDICTED OBJECT DETAILS</h4>
        </div>
        <div id="predictedObjects" class="row">
            @foreach (var item in Model.Detail.PredictedObjects)
            {
                var url = $"{blobStorageUrl}/{Model.Name}/{item.FileName}";
                <div class="col-6 col-md-3 flex-row justify-content-center d-flex" style="padding-top:20px;">
                    <div class="card">
                        <img alt="@item.ClassName" class="img-thumbnail card-img-top w-100 d-block" src="@url">
                        <div class="card-body">
                            <h5 class="card-title">Type: @item.ClassName</h5>
                            @if (item.Text != null)
                            {
                                if (String.Join(" ", item.Text.ToArray()) != "")
                                {
                                    <h5 class="card-title">Text: @String.Join(" ", item.Text.ToArray())</h5>
                                }
                            }
                            <h5 class="card-title">Probability: @Math.Round(item.Probability * 100, 2) %</h5>

                        </div>
                    </div>

                </div>
            }
        </div>



    </div>

Sketch2Code/Sketch2Code.Web/Views/App/Details_old.cshtml
@model Sketch2Code.Web.Models.PredictionDetailsViewModel
@{
    var blobStorageUrl = System.Configuration.ConfigurationManager.AppSettings["storageUrl"];
    var originalFileName = $"{blobStorageUrl}/{Model.Name}/original.png";
    var predictedFileName = $"{blobStorageUrl}/{Model.Name}/predicted.png";
    Layout = "~/Views/Shared/_LayoutDetails.cshtml";
}

@section Steps
{

    <div id="upload" class="d-flex pd-top1">
        <div>
            <span class="dot active"><span class="header-number active">1</span></span>
        </div>
        <p class="flex-shrink-0 header-txt active">UPLOAD DESIGN</p>
    </div>
    <hr>
    <div class="d-flex pd-top2">
        <div>
            <span class="dot active"><span class="header-number active">2</span></span>
        </div>
        <p class="flex-shrink-0 header-txt active">SKETCH2CODE IS AT WORK!</p>
    </div>
    <hr>
    <div id="download" class="d-flex pd-top3">
        <div>
            <span class="dot active"><span class="header-number active">3</span></span>
        </div>
        <p class="flex-shrink-0 header-txt active">DOWNLOAD YOUR HTML</p>
    </div>
}


    <div class="row">

        <div class="col col-0 col-md-0">
            <div class="row justify-content-center">

                <h1 class="text-center justify-content-center"><span class="main_sketch">Sketch</span><span class="text-white main_two">2</span><span class="main_code">Code</span></h1>

            </div>
            <div class="row justify-content-center">
                <div class="col col-12 col-md-12">
                    <h2 class="text-center text-white justify-content-center main_subtitle" id="main_01_subtitle">Transform any hands-drawn design into a HTML code with AI.</h2>
                </div>
            </div>
        </div>

    </div>




<div class="container-fluid">
    <div class="row detailsPage_row">
      
        <div class="col justify-content-center col-12 col-sm-12 col-md-5 col-lg-5 col-xl-5">
            <h3 class="text-top">SKETCH</h3><img alt="Your sketch" class="img-fluid" src="@originalFileName" />
        </div>
        <div class="col align-self-center text-center rotation-wrapper-outer">
            <div class="rotation-wrapper-inner"><img alt="Arrow" class="img-fluid img_arrow" src="~/Content/img/arrow_details.svg"></div>
        </div>
        <div class="col col-12 col-sm-12 col-md-5 col-lg-5 col-xl-5">
            <h3 class="text-top">PREDICTED</h3><img alt="Your predicted skecth" class="img-fluid" src="@predictedFileName" />
        </div>
        @*<div class="col align-self-center text-center rotation-wrapper-outer">
                    <div class="rotation-wrapper-inner"><img class="img-fluid img_arrow" src="assets/img/arrow_details.svg"></div>
                </div>
                <div class="col col-12 col-sm-12 col-md-3 col-lg-3 col-xl-3">
                     <h3 class="text-top">HTML</h3><img class="img-fluid" src="@Url.RouteUrl(new { action = "file", container = Model.Name, fileName = "html_result.png"})"/>
            </div>*@

       
    </div>
</div>
<div class="container-fl">
    <div class="row3 justify-content-center">
   
        <div class="col col-10 col-sm-10 col-md-10 col-lg-10 col-xl-10">
            <h4 id="text-predicted" class="d-flex justify-content-center">PREDICTED OBJECT DETAILS</h4>
            <div class="row">
                @foreach (var item in Model.Detail.PredictedObjects)
                {
                    var url = $"{blobStorageUrl}/{Model.Name}/{item.FileName}";
                    <div class="col flex-row justify-content-center d-flex col-lg-3 col-md-3 col-sm-6 col-6" style="padding-top:20px;">
                        <div class="card">
                            <img alt="@item.ClassName" class="img-thumbnail card-img-top w-100 d-block" src="@url">
                            <div class="card-body">
                                <h5 class="card-title">Type: @item.ClassName</h5>
                                @if (item.Text != null)
                                {
                                    if (String.Join(" ", item.Text.ToArray()) != "")
                                    {
                                        <h5 class="card-title">Text: @String.Join(" ", item.Text.ToArray())</h5>
                                    }
                                }
                                <h5 class="card-title">Probability: @Math.Round(item.Probability * 100, 2) %</h5>

                            </div>
                        </div>

                    </div>
                }
            </div>
        </div>
     
    </div>
</div>

Sketch2Code/Sketch2Code.Web/Views/App/Index.cshtml
@{
    Layout = "~/Views/Shared/_main.cshtml";
}

<div class="container pb-0">
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <div class="row">
            <!-- Indicators -->
            <ol class="carousel-indicators">
                <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                <li data-target="#myCarousel" data-slide-to="1"></li>
                <li data-target="#myCarousel" data-slide-to="2"></li>
            </ol>
        </div>

        <!-- Wrapper for slides -->
        <div class="carousel-inner">
            <div class="item active">
                <div class="container text-center">
                    <img src="../Content/img/sampleDesigns/sample1.jpg" alt="Los Angeles" style="width:200px;height:200px">
                    <form enctype="multipart/form-data" method="post" action="/app/step2fromsample/sample1">
                        <input type="submit" value="Use this sample" class="btn btn-success mt-3" />
                    </form>

                </div>
            </div>

            <div class="item">
                <div class="container text-center">
                    <img src="../Content/img/sampleDesigns/sample2.jpg" alt="Los Angeles" style="width:200px;height:200px">
                    <form enctype="multipart/form-data" method="post" action="/app/step2fromsample/sample2">
                        <input type="submit" value="Use this sample" class="btn btn-success mt-3" />
                    </form>
                </div>
            </div>

            <div class="item">
                <div class="container text-center">
                    <img src="../Content/img/sampleDesigns/sample3.jpg" alt="Los Angeles" style="width:200px;height:200px">
                    <form enctype="multipart/form-data" method="post" action="/app/step2fromsample/sample3">
                        <input type="submit" value="Use this sample" class="btn btn-success mt-3" />
                    </form>
                </div>
            </div>
        </div>

        <!-- Left and right controls -->
        <a class="left carousel-control" href="#myCarousel" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#myCarousel" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</div>
</div>

<div id="actions" class="container-fluid">
    <div class="row">
        <div class="col d-flex flex-column justify-content-center">
            <form id="file_upload" class="center-hz-right" enctype="multipart/form-data" method="post" action="@Url.RouteUrl("ready-to-start")">
                <label for="imageData">
                    <img alt="Upload sketch" src="/content/img/button_upload.svg" width="250px">
                    <input id="imageData" class="custom-file-input" name="imageData" type="file" accept="image/*" onchange="submitFile();" />
                </label>
            </form>
        </div>
        <div class="col col-md-1 d-flex flex-column justify-content-center hidden-responsive"><span class="main-or">OR</span></div>
        <div class="col d-flex flex-column justify-content-center hidden-responsive">
            <a href="@Url.RouteUrl("camera")" id="main_01_button_pic"><img alt="Take a picture" src="/content/img/button_picture.svg" width="250px"></a>
        </div>
    </div>
</div>

<div id="howItWorks" class="container">
    <h3 class="text-center">Experiment Workflow</h3>

    <div class="container">
        <div id="step1" class="row">
            <div class="col">
                <div class="title">
                    <div class="number">01</div>
                    <h5>
                        Detect Design Patterns
                    </h5>
                </div>
                <p>
                    A Custom Vision Model trained to perform object recognition against
                    HTML hand drawn patterns is used to detect meaningful design elements into an image.&nbsp;
                </p>
            </div>
            <div class="col align-middle"><img src="/Content/img/how_to_01PNG.png" /></div>
        </div>
    </div>


    <div class="container">
        <div id="step2" class="row">
            <div class="col">
                <img alt="Understand handwritten text" src="/Content/img/how_to_02PNG.png">
            </div>
            <div class="col">
                <div class="title">
                    <div class="number">02</div>
                    <h5>
                        Understand handwritten text
                    </h5>
                </div>
                <p>
                    Each detected element is passed through a Text Recognition Service to extract handwritten content.
                </p>
            </div>
        </div>
    </div>

    <div class="container">
        <div id="step3" class="row">
            <div class="col">
                <div class="title">
                    <div class="number">03</div>
                    <h5>
                        Understand Structure
                    </h5>
                </div>
                <p>
                    The information of the detected objects and their position inside the
                    image is feed into an algorithm that generates underlying structure.
                </p>
            </div>
            <div class="col align-middle"><img alt="Understand Structure" src="/Content/img/how_to_03PNG.png"></div>
        </div>
    </div>

    <div class="container">
        <div id="step4" class="row">
            <div class="col">
                <img alt="Understand handwritten text" src="/Content/img/how_to_04PNG.png">
            </div>
            <div class="col">
                <div class="title">
                    <div class="number">04</div>
                    <h5>
                        Build HTML
                    </h5>
                </div>
                <p>
                    A valid HTML is generated accordingly to the detected layout containing the detected design elements.
                </p>
            </div>
        </div>
    </div>
</div>

@section Scripts
{
    <script type="text/javascript">
        function submitFile() {
            $("#file_upload").submit();
        }
    </script>
}

Sketch2Code/Sketch2Code.Web/Views/App/Loader1.cshtml
@section Steps
{
    <div id="upload" class="d-flex">
        <div>
            <span class="dot active"><span class="header-number active">1</span></span>
        </div>
        <p class="flex-shrink-0 header-text active">UPLOAD DESIGN</p>
    </div>
    <hr>
    <div class="d-flex">
        <div>
            <span class="dot active"><span class="header-number">2</span></span>
        </div>
        <p class="flex-shrink-0 header-text active">SKETCH2CODE IS AT WORK!</p>
    </div>
    <hr>
    <div id="download" class="d-flex">
        <div>
            <span class="dot"><span class="header-number">3</span></span>
        </div>
        <p class="flex-shrink-0 header-text">DOWNLOAD YOUR HTML</p>
    </div>
}
<div class="row">
    <div class="col col-0 col-md-2 col-lg-3"></div>
    <div class="col">
        <div class="justify-content-center d-flex">
            <h1 ><span class="main_sketch">Sketch</span><span class="text-white main_two">2</span><span class="main_code">Code</span></h1>
            
        </div>
        <h2 class="text-center text-white justify-content-center main_subtitle" id="main_03_subtitle">Please wait...</h2>
    </div>
    <div class="col col-0 col-md-2 col-lg-3"></div>
</div>
<div class="row" id="main_03_rowBottom">
    <div class="col col-0 col-md-1"></div>
    <div class="col d-flex justify-content-center align-items-center col-12 col-md-10" id="main_03_colBottom">
        <div class="text-center main_yourSketch">
            <p class="main_03_choices">YOUR SKETCH</p><img alt="Your sketch" class="img-fluid" src="/content/img/step2_leftCircle.png">
        </div>
        <hr class="main_03_lines">
        <div class="d-flex justify-content-center"><div class="loader"></div></div>
        <hr class="main_03_lines">
        <div class="text-center main_yourHtml">
            <p class="main_03_choices">YOUR HTML CODE</p><img alt="Your forthcoming html" class="img-fluid" src="/content/img/step2_rightCircle%20(2).png">
        </div>
    </div>
    <div class="col col-0 col-md-1"></div>
</div>

Sketch2Code/Sketch2Code.Web/Views/App/Step3.cshtml
@model Sketch2Code.Web.Models.ContentViewModel

@section Message
    {
    <h3 class="subtitle2 text-white">Working on your Sketch. Please wait...</h3>
}


<div id="actions" class="container-fluid">
    <div class="row justify-content-center pb-5">
        <img alt="Your sketch" class="img-load-responsive" src="@String.Format("https://sketch2code.blob.core.windows.net/{0}/original.png", Model.CorrelationId)" >
    </div>
    <div class="row justify-content-center pb-4">
        <img alt="Loading" class="img-responsive-status" src="/content/img/loader.gif" />
    </div>
</div>

<input type="hidden" id="correlationId" value="@Model.CorrelationId" />
<div style="margin-left:-10000px;float:left;" id="htmlContainer">
</div>
@section Scripts
{
    <script>
        $(document).ready(function () {
            $("#step2").addClass("active");
            $("#step2txt").addClass("active");
            $("#step1").removeClass("active");
            $("#step1txt").removeClass("active");

        });
    </script>

    <script src="~/Scripts/html2canvas.min.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {

            var uploadUrl = "@Url.RouteUrl("upload")";
            var formData = new FormData();
            formData.append('correlationId', $("#correlationId").val());
            $.ajax({
                url: uploadUrl,
                data: formData,
                processData: false,
                contentType: false,
                type: 'POST',
                success: function (data) {
                    document.querySelector("#htmlContainer").innerHTML = data.generatedHtml;
                    generateHtml();
                }
            });
        });

        function generateHtml() {
            html2canvas(document.querySelector("#generatedHTML")).then(function (canvas) {
                // Export the canvas to its data URI representation
                var base64image = canvas.toDataURL("image/png");
                base64image = base64image.replace('data:image/png;base64,', '');
                sendFileToServer(base64image);
            });
        }

        function sendFileToServer(base64image) {
            var routeUrl = "/generated-html/";
            $.ajax({
                type: "POST",
                url: '@Url.Action("SaveFile", "App")',
                data: {
                    imgBase64: base64image, folderId: '@Model.CorrelationId'
                },
                success: function (o) {
                    window.location.href = routeUrl + '@Model.CorrelationId';
                }
            });
        }
    </script>
}

Sketch2Code/Sketch2Code.Web/Views/App/Step5_old.cshtml
@model Sketch2Code.Web.Models.GeneratedHtmlModel
@{
    ViewBag.Title = "Step5";
    Layout = null;
}

<html>
<head>
    <script src="~/Scripts/html2canvas.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css"
          integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
</head>
<body>
    <div style="margin-left:-10000px;float:left;">
        @Html.Raw(Model.Html)
    </div>

    <img id="htmlOriginalImage" width="400px" src='@String.Format("https://sketch2code.azurewebsites.net/template/file?container={0}&fileName=original.png", Model.FolderId)'/>

    <img id="htmlImage" width="400px" />

    <script>
        html2canvas(document.querySelector("#generatedHTML")).then(function (canvas) {
            // Export the canvas to its data URI representation
            var base64image = canvas.toDataURL("image/png");
            base64image = base64image.replace('data:image/png;base64,', '');
            sendFileToServer(base64image);
        });

        function sendFileToServer(base64image) {
            $.ajax({
                type: "POST",
                url: '@Url.Action("SaveFile", "App")',
                data: {
                    imgBase64: base64image, folderId: '@Model.FolderId'
                }
            }).done(function (o) {
                $('#htmlImage').attr("src", o);
            });
        }
    </script>
</body>
</html>