Sketch2Code/Sketch2Code.Web/Controllers/LayoutController.cs
using Sketch2Code.Core;
using Sketch2Code.Core.Helpers;
using Sketch2Code.Core.Services.Interfaces;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using Sketch2Code.Web.Helpers;
using Sketch2Code.Core.BoxGeometry;
using System.Text;
using System.Collections.Generic;
using System.Net.Http;
using System.Net;

namespace Sketch2Code.Web.Controllers
{
    public class LayoutController : BaseController
    {
        IObjectDetectionAppService _objectDetectionAppService;
        public LayoutController()
        {
            _objectDetectionAppService = new ObjectDetectionAppService();
        }

        public async Task<ActionResult> Details(string id)
        {
            var objects = await _objectDetectionAppService.GetPredictionAsync(id);
            var model = objects.PredictedObjects.Where(p => p.ClassName!=Controls.Table).ToList();
            return View(model);
        }

        public async Task<ActionResult> GroupBox(string id)
        {
            var objects = await _objectDetectionAppService.GetPredictionAsync(id);

            return View(objects.GroupBox.FirstOrDefault());
        }

        public async Task<FileResult> Result(string id)
        {
            var objects = await _objectDetectionAppService.GetPredictionAsync(id);
            var result = this.RenderViewToString<GroupBox>("/Views/Layout/RawGroupBox.cshtml", objects.GroupBox.FirstOrDefault());
            var buffer = Encoding.UTF8.GetBytes(result);

            return File(buffer, System.Net.Mime.MediaTypeNames.Text.Html, "result.html");
        }

        public async Task<ActionResult> RawGroupBox(string id)
        {
            var objects = await _objectDetectionAppService.GetPredictionAsync(id);
            return View(objects.GroupBox.FirstOrDefault());
        }
    }
}

Sketch2Code/Sketch2Code.Web/Controllers/TemplateController.cs
using Sketch2Code.Core;
using Sketch2Code.Core.Services.Interfaces;
using Sketch2Code.Web.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Sketch2Code.Web.Controllers
{
    public class TemplateController : BaseController
    {
        IObjectDetectionAppService _objectDetectionAppService;
        public TemplateController()
        {
            _objectDetectionAppService = new ObjectDetectionAppService();
        }
        // GET: Template
        public async Task<ActionResult> Index()
        {
            var list = (await _objectDetectionAppService.GetPredictionsAsync()).ToList();
            list = list.Take(15).ToList();
            var model = list.ToList().ConvertAll((container) =>
            {
                return new PredictionViewModel(container.Name, container.Properties.LastModified?.DateTime);
            });
            return View(model);
        }
        public ActionResult Uploader()
        {
            return View();
        }
        public ActionResult Prueba()
        {
            return View();
        }
        [HttpPost]
        public async Task<ActionResult> Uploader(ContentViewModel model)
        {
            byte[] buffer = null;
            HttpPostedFileBase file = Request.Files["ImageData"];
            var url = ConfigurationManager.AppSettings["Sketch2CodeAppFunctionEndPoint"];

            //file or base64 content
            if (file == null) //check if image is submitted as base64
            {
                var image = Request["ImageData"];
                if (!String.IsNullOrWhiteSpace(image))
                {
                    buffer = Convert.FromBase64String(image);
                }
                else
                {
                    throw new ApplicationException("No file or base64 content found");
                }
            }
            else
            {
                buffer = new byte[file.ContentLength];
                using (var ms = new MemoryStream())
                {
                    await file.InputStream.CopyToAsync(ms);
                    buffer = ms.ToArray();
                }
            }

            using (HttpClient client = new HttpClient())
            {
                var content = new ByteArrayContent(buffer);
                HttpResponseMessage respon = await client.PostAsync(url, content);
                var responseBody = await respon.Content.ReadAsStringAsync();
                var jsonResponse = await Task.Run(() => JsonConvert.DeserializeObject<string>(responseBody));
                string correlationID = jsonResponse;
                return RedirectToAction("GroupBox", "Layout", new { id = correlationID });
            }
        }
        public async Task<ActionResult> Details(string id)
        {
            var model = new PredictionDetailsViewModel();

            model.Detail = await _objectDetectionAppService.GetPredictionAsync(id);

            if (model.Detail?.PredictedObjects != null && model.Detail.PredictedObjects.Any())
            {
                model.Name = id;
            }

            return View(model);
        }
        public async Task<FileContentResult> File(string container, string fileName)
        {
            var fileContent = await this._objectDetectionAppService.GetFile(container, fileName);
            return new FileContentResult(fileContent, "image/png");
        }
        public async Task<FileContentResult> FileJson(string container)
        {

            var fileContent = await this._objectDetectionAppService.GetFile(container, "results.json");
            return new FileContentResult(fileContent, "application/json");
        }
    }
}

Sketch2Code/Sketch2Code.Web/Views/Shared/_Button.cshtml
@model Sketch2Code.Core.Entities.PredictedObject
<button class="btn btn-primary">@String.Join(" ", Model.Text)</button>

Sketch2Code/Sketch2Code.Web/Views/Shared/_CheckBox.cshtml
@model Sketch2Code.Core.Entities.PredictedObject

<label><input type="checkbox" /> @String.Join(" ", Model.Text)</label>

Sketch2Code/Sketch2Code.Web/Views/Shared/_ComboBox.cshtml
@model Sketch2Code.Core.Entities.PredictedObject
<div class="dropdown">
    <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
        @String.Join(" ", Model.Text)
    </button>
    <div class="dropdown-menu">
        <a class="dropdown-item" href="#"></a>

    </div>
 
</div>

   

Sketch2Code/Sketch2Code.Web/Views/Shared/_DebugLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Sketch2Code - Transform sketches into HTML markup automagically!</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/octicons.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    @RenderSection("Content", required: false);
    <script type='text/javascript'>
        var appInsights=window.appInsights||function(config)
        {
            function r(config){ t[config] = function(){ var i = arguments; t.queue.push(function(){ t[config].apply(t, i)})} }
            var t = { config:config},u=document,e=window,o='script',s=u.createElement(o),i,f;for(s.src=config.url||'//az416426.vo.msecnd.net/scripts/a/ai.0.js',u.getElementsByTagName(o)[0].parentNode.appendChild(s),t.cookie=u.cookie,t.queue=[],i=['Event','Exception','Metric','PageView','Trace','Ajax'];i.length;)r('track'+i.pop());return r('setAuthenticatedUserContext'),r('clearAuthenticatedUserContext'),config.disableExceptionTracking||(i='onerror',r('_'+i),f=e[i],e[i]=function(config, r, u, e, o) { var s = f && f(config, r, u, e, o); return s !== !0 && t['_' + i](config, r, u, e, o),s}),t
        }({
            instrumentationKey:'0bf8d80a-82a1-4966-947c-9d7b15bf42d8'
        });

        window.appInsights=appInsights;
        appInsights.trackPageView();
    </script>
</head>
<body>
    <div class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggler" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="navbar-toggler-icon"></span>
                    <span class="navbar-toggler-icon"></span>
                    <span class="navbar-toggler-icon"></span>
                </button>
                @Html.ActionLink("Sketch2Code - Transform sketches into HTML markup automagically!", "Index", "Template", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="collapse navbar-collapse">
                <ul class="navbar-nav mr-auto"></ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Sketch2Code</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.0.0.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>
</body>
</html>

Sketch2Code/Sketch2Code.Web/Views/Shared/_FlatLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>HTML Result</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" 
          integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
</head>
<body>
    <div class="container body-content">
        @RenderBody()
    </div>
</body>
</html>

Sketch2Code/Sketch2Code.Web/Views/Shared/_Heading.cshtml
@model Sketch2Code.Core.Entities.PredictedObject
<h1>@String.Join(" ", Model.Text)</h1>

Sketch2Code/Sketch2Code.Web/Views/Shared/_Image.cshtml
@model Sketch2Code.Core.Entities.PredictedObject
@{ 
    var width = $"{Convert.ToInt32(Model.BoundingBox.Width)}px";
    var height = $"{Convert.ToInt32(Model.BoundingBox.Height)}px";
}

<img alt="Image html" width="90%" height="90%" style="max-height:500px;max-width:500px;" src="/Content/img/fake_img.svg"/>

Sketch2Code/Sketch2Code.Web/Views/Shared/_Label.cshtml
@model Sketch2Code.Core.Entities.PredictedObject
<label>@String.Join(" ", Model.Text)</label>

Sketch2Code/Sketch2Code.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">


    <title>@ViewBag.Title - Sketch2Code - Transform sketches into HTML markup automagically!</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <link href="~/Content/octicons.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700,800">
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <script src="~/Scripts/html2canvas.min.js"></script>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    @RenderSection("Content", required: false)
    <script type='text/javascript'>
        var appInsights = window.appInsights || function (config) {
            function r(config) { t[config] = function () { var i = arguments; t.queue.push(function () { t[config].apply(t, i) }) } }
            var t = { config: config }, u = document, e = window, o = 'script', s = u.createElement(o), i, f; for (s.src = config.url || '//az416426.vo.msecnd.net/scripts/a/ai.0.js', u.getElementsByTagName(o)[0].parentNode.appendChild(s), t.cookie = u.cookie, t.queue = [], i = ['Event', 'Exception', 'Metric', 'PageView', 'Trace', 'Ajax']; i.length;)r('track' + i.pop()); return r('setAuthenticatedUserContext'), r('clearAuthenticatedUserContext'), config.disableExceptionTracking || (i = 'onerror', r('_' + i), f = e[i], e[i] = function (config, r, u, e, o) { var s = f && f(config, r, u, e, o); return s !== !0 && t['_' + i](config, r, u, e, o), s }), t
        }({
            instrumentationKey: '0bf8d80a-82a1-4966-947c-9d7b15bf42d8'
        });

        window.appInsights = appInsights;
        appInsights.trackPageView();
    </script>
</head>
<body>

    <div id="disclaimer" class="disclaimer text-white hide" aria-hidden="true">
        This site uses cookies for analytics, personalized content and ads. By continuing to browse this site, you agree to this use.
        <a class="learn-more" href="https://privacy.microsoft.com/en-US/">Learn more</a>
        <button class="close" id="cookie-consent" aria-label="Close">X</button>
    </div>
    <div>
       
            <div class="container-fl">
                <div class="row header-row">
                    <div class="col-lg-2 col-xl-2 col-md-2 col-6"><img alt="Microsoft Logo" class="img-fluid float-left d-flex flex-column justify-content-end center-logo" src="~/content/img/logo_MS.png"></div>
                    <div class="col header-column justify-content-center">
                        @RenderSection("Steps")
                    </div>
                    <div class="col-lg-2 col-xl-2 col-md-2 col-6 float-left d-flex flex-column justify-content-start"><a class="link d-flex flex-column justify-content-end" target="_blank" href="https://www.ailab.microsoft.com/">AI Lab</a></div>

                </div>


            </div>
            <div class="container-fl">
                @RenderBody()
            </div>
            <div class="fixed-bottom">
                <div class="row">
                    <div class="col float-left d-flex flex-column justify-content-end align-items-start"><img alt="Microsoft Logo" class="img-fluid float-left d-flex flex-column justify-content-end center-logo-bottom" src="~/content/img/logo_MS.png"></div>
                    <div class="col"><img alt="Logo web" class="img-fluid float-right hidden-responsive" src="/content/img/img_spareMobile.svg" id="img_bottomRight"></div>
                </div>
                <div class="row2">
                    <div class="col footer step">
                        <span>Your picture may be used to improve the underlying AI.</span>

                        <div class="footer-links">
                            <div class="col col-0 line-block" style="margin-left:6px!important; margin-bottom:2em;"></div>
                            <div class="col col-0" style="margin-bottom:2em;"><a target="_blank" href="https://www.ailab.microsoft.com/">AI Lab</a></div>
                            <div class="col col-0 line-block" style="margin-bottom:2em;"><a target="_blank" href="https://support.microsoft.com/en-us/contactus">Contact Us</a></div>
                            <div class="col col-0 line-block" style="margin-bottom:2em;"><a target="_blank" href="https://go.microsoft.com/fwlink/?LinkId=521839">Privacy &amp; Cookies</a></div>
                            <div class="col col-0 line-block" style="margin-bottom:2em;"><a target="_blank" href="https://go.microsoft.com/fwlink/?LinkID=206977">Terms of use</a></div>
                            <div class="col col-0 line-block" style="margin-bottom:2em;"><a target="_blank" href="https://www.microsoft.com/trademarks">Trademarks</a></div>
                            <div class="col col-0 line-block" style="margin-bottom:2em;"><span>© Microsoft 2018<br></span></div>
                            <div class="col col-0 line-block"></div>



                        </div>
                    </div>
                </div>
            </div>
        </div>


    <script src="~/Scripts/jquery-3.0.0.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>
    @RenderSection("Scripts", required: false)


    <script type="text/javascript">
        var consent = function () {
            return (document.cookie.indexOf("Sketchconsent") != -1);
        }

        $(document).ready(function () {

            var setConsentCookie = function () {
                var d = new Date();
                d.setTime(d.getTime() + (99999 * 24 * 60 * 60 * 1000));
                var expires = "expires=" + d.toUTCString();
                document.cookie = "Sketchconsent=1;" + expires + ";path=/";
                $("#disclaimer").hide();
            };

            if (!consent()) {
                $("#disclaimer").show();
                $("#cookie-consent").click(function () {
                    setConsentCookie();
                });
                $("a").click(function () {
                    setConsentCookie();
                });
            }
        });

    </script>



    <!--Adobe analytics-->
    <script src="https://az725175.vo.msecnd.net/scripts/jsll-4.js" type="text/javascript">
    </script>
    <script>
        const config = {
            syncMuid: awa.utils.isValueAssigned(window.awa.cookie.getCookie('Sketchconsent')),
            userConsentCookieName: 'Sketchconsent',
            autoCapture: {
                lineage: true,
                scroll: true
            },
            coreData: {
                appId: 'Sketch2Code',
                env: 'prod',
                market: 'en-us',
                pageName: 'Sketch2Code',
                pageType: 'html'
            },
            useShortNameForContentBlob: true
        };

        if (consent())
            awa.init(config);


    </script>

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-121469252-4"></script>
    <script>
        if (consent()) {
            window.dataLayer = window.dataLayer || [];
            function gtag() { dataLayer.push(arguments); }
            gtag('js', new Date());

            gtag('config', 'UA-121469252-4');
        }

    </script>

    <!-- Facebook Pixel Code -->
    <script>
        if (consent()) {
            !function (f, b, e, v, n, t, s) {
                if (f.fbq) return; n = f.fbq = function () {
                    n.callMethod ?
                        n.callMethod.apply(n, arguments) : n.queue.push(arguments)
                };
                if (!f._fbq) f._fbq = n; n.push = n; n.loaded = !0; n.version = '2.0';
                n.queue = []; t = b.createElement(e); t.async = !0;
                t.src = v; s = b.getElementsByTagName(e)[0];
                s.parentNode.insertBefore(t, s)
            }(window, document, 'script',
                'https://connect.facebook.net/en_US/fbevents.js');
            fbq('init', '435868603227390');
            fbq('track', 'PageView');
        }

    </script>
    <noscript>
        <img height="1" width="1" style="display:none"
             src="https://www.facebook.com/tr?id=435868603227390&ev=PageView&noscript=1" />
    </noscript>
    <!-- End Facebook Pixel Code -->
    <!-- Twitter universal website tag code -->
    <script>
        if (consent()) {
            !function (e, t, n, s, u, a) {
                e.twq || (s = e.twq = function () {
                    s.exe ? s.exe.apply(s, arguments) : s.queue.push(arguments);
                }, s.version = '1.1', s.queue = [], u = t.createElement(n), u.async = !0, u.src = '//static.ads-twitter.com/uwt.js',
                    a = t.getElementsByTagName(n)[0], a.parentNode.insertBefore(u, a))
            }(window, document, 'script');
            // Insert Twitter Pixel ID and Standard Event data below
            twq('init', 'nv9r3');
            twq('track', 'PageView');
        }

    </script>
    <!-- End Twitter universal website tag code -->
    <!-- Twitter universal website tag code -->
    <img height="1" width="1" style="display:none;" alt="" src="https://analytics.twitter.com/i/adsct?p_id=Twitter&p_user_id=0&txn_id=nv9r3&events=%5B%5B%22pageview%22%2Cnull%5D%5D&tw_sale_amount=0&tw_order_quantity=0" />
    <img height="1" width="1" style="display:none;" alt="" src="//t.co/i/adsct?p_id=Twitter&p_user_id=0&txn_id=nv9r3&events=%5B%5B%22pageview%22%2Cnull%5D%5D&tw_sale_amount=0&tw_order_quantity=0" />
    <!-- End Twitter universal website tag code -->
    <!-- LinkedIn-->
    <script type="text/javascript">
        _linkedin_data_partner_id = "7850";
    </script>
    <script type="text/javascript">
        if (consent()) {
            (function () {
                var s = document.getElementsByTagName("script")[0];
                var b = document.createElement("script");
                b.type = "text/javascript"; b.async = true;
                b.src = "https://snap.licdn.com/li.lms-analytics/insight.min.js";
                s.parentNode.insertBefore(b, s);
            })();
        }
    </script>
    <noscript>
        <img height="1" width="1" style="display:none;" alt="" src="https://dc.ads.linkedin.com/collect/?pid=7850&fmt=gif" />
    </noscript>
</body>
</html>

Sketch2Code/Sketch2Code.Web/Views/Shared/_Paragraph.cshtml
@model Sketch2Code.Core.Entities.PredictedObject


    @String.Concat("Lorem ipsum dolor sit amet, consectetur adipiscing elit")
    <br />
    @String.Concat("sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.")
    <br />
    @String.Concat("Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris")

Sketch2Code/Sketch2Code.Web/Views/Shared/_RadioButton.cshtml
@model Sketch2Code.Core.Entities.PredictedObject
<label><input type="radio" /> @String.Join(" ", Model.Text)</label>

Sketch2Code/Sketch2Code.Web/Views/Shared/_TextBox.cshtml
@model Sketch2Code.Core.Entities.PredictedObject
@Bootstrap.Input()